version: "3.7"
services:
    web:
        build: .
        ports: 
            - "8001:80"
        container_name: web-php
        volumes:
            - ./www:/var/www/html/
        links:
            - mysql
    mysql:
        image: mysql
        ports: 
            - "3306:3306"
        container_name: mysql
        environment:
            MYSQL_DATABASE: sqli
            MYSQL_USER: admin
            MYSQL_PASSWORD: A12345678
            MYSQL_ROOT_PASSWORD: A12345678
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - mysql_data:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links: 
            - mysql:mysql
        ports:
            - 8000:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: A123345678
            MYSQL_ROOT_PASSWORD: A123345678
volumes:
    mysql_data: