version: "3.7"
services:
    web:
        build: .
        restart: always
        ports: 
            - "8001:80"
        container_name: web-php
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - mysql
        networks: 
            - frontend
    mysql:
        image: mysql:5.7
        ports: 
            - 3306:3306
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: sqli
            MYSQL_USER: admin
            MYSQL_PASSWORD: A12345678
            MYSQL_ROOT_PASSWORD: A12345678
        volumes:
            - ./:/docker-entrypoint-initdb.d
            - mysql_data:/var/lib/mysql
        networks:
            - frontend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on: 
            - mysql
        ports:
            - 8888:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: A123345678
            MYSQL_ROOT_PASSWORD: A123345678
            PMA_HOST: mysql
        networks:
            - frontend
volumes:
    mysql_data:
networks: 
    frontend:
        external: true